FROM quay.io/ascend/cann:test_8.1.RC1.alpha002-910b-openeuler24.03-py3.10

ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
ARG COMPILE_CUSTOM_KERNELS=1

ENV COMPILE_CUSTOM_KERNELS=${COMPILE_CUSTOM_KERNELS}

RUN yum update -y && \
    yum install -y python3-pip git vim wget net-tools gcc gcc-c++ make cmake numactl-devel && \
    rm -rf /var/cache/yum

RUN pip config set global.index-url ${PIP_INDEX_URL}

WORKDIR /workspace

# Install vLLM
ARG VLLM_REPO=https://github.com/vllm-project/vllm.git
ARG VLLM_TAG=v0.8.4
ARG VLLM_ASCEND_REPO=https://github.com/vllm-project/vllm-ascend.git
ARG VLLM_ASCEND_TAG=main

RUN git clone --depth 1 $VLLM_ASCEND_REPO --branch $VLLM_ASCEND_TAG /workspace/vllm-ascend
RUN git clone --depth 1 $VLLM_REPO --branch $VLLM_TAG /workspace/vllm

# In x86, triton will be installed by vllm. But in Ascend, triton doesn't work correctly. we need to uninstall it.
RUN VLLM_TARGET_DEVICE="empty" python3 -m pip install -e /workspace/vllm/ --extra-index https://download.pytorch.org/whl/cpu/ && \
    python3 -m pip uninstall -y triton && \
    python3 -m pip cache purge

# Install vllm-ascend
RUN source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    source /usr/local/Ascend/nnal/atb/set_env.sh && \
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/Ascend/ascend-toolkit/latest/`uname -i`-linux/devlib && \
    export export CPLUS_INCLUDE_PATH=/usr/lib/gcc/x86_64-openEuler-linux/12/../../../../include/c++/12:/usr/lib/gcc/x86_64-openEuler-linux/12/../../../../include/c++/12/x86_64-openEuler-linux:/usr/lib/gcc/x86_64-openEuler-linux/12/../../../../include/c++/12/backward:/usr/lib/gcc/x86_64-openEuler-linux/12/include:/usr/local/include:/usr/include && \
    python3 -m pip install -v -e /workspace/vllm-ascend/ --extra-index https://download.pytorch.org/whl/cpu/ && \
    python3 -m pip cache purge

# Install modelscope (for fast download) and ray (for multinode)
RUN python3 -m pip install modelscope ray && \
    python3 -m pip cache purge

CMD ["/bin/bash"]